# cloudbuild.yaml

# サブスティテューション変数の定義
substitutions:
  _SERVICE_NAME: ''               # マイクロサービス名（例: service-a）
  _SERVICE_DIR: ''                # マイクロサービスのディレクトリパス（例: services/service-a）
  _ARTIFACT_REGISTRY: 'artifact-registry-repo'  # Artifact Registryのリポジトリ名
  _SERVICE_ACCOUNT_NAME: ''       # サービスアカウント名（例: service-a-account@your-project.iam.gserviceaccount.com）

steps:
  # コンテナイメージをビルド
  - name: "gcr.io/cloud-builders/docker"
    dir: "${_SERVICE_DIR}"
    args:
      [
        "build",
        "-t",
        "asia-northeast1-docker.pkg.dev/microservice-448705/${_ARTIFACT_REGISTRY}/${_SERVICE_NAME}:latest",
        ".",
      ]

  # コンテナイメージをArtifact Registryにプッシュ
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "asia-northeast1-docker.pkg.dev/microservice-448705/${_ARTIFACT_REGISTRY}/${_SERVICE_NAME}:latest",
      ]

  # Cloud Runにデプロイ
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "${_SERVICE_NAME}",
        "--image",
        "asia-northeast1-docker.pkg.dev/microservice-448705/${_ARTIFACT_REGISTRY}/${_SERVICE_NAME}:latest",
        "--platform",
        "managed",
        "--allow-unauthenticated",
        "--ingress",
        "all",
        "--region",
        "asia-northeast1",
        "--project",
        "microservice-448705",
        "--quiet"
      ]

# サービスアカウントの指定
serviceAccount: "projects/microservice-448705/serviceAccounts/${_SERVICE_ACCOUNT_NAME}"

# ビルドオプションの設定
options:
  logging: CLOUD_LOGGING_ONLY